---
name: iOS

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Cache CMake build folder
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ github.workflow }}-v4-${{ github.sha }}
        restore-keys: ${{ github.workflow }}-v4-

    - name: Configure CMake
      shell: bash
      working-directory: ${{github.workspace}}
      run: |
        cmake \
          -S . \
          -B build \
          -D CMAKE_TOOLCHAIN_FILE=../CMake/platforms/ios.toolchain.cmake \
          -D ENABLE_BITCODE=0 \
          -D PLATFORM=OS64

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        cmake \
          --build build \
          -j $(sysctl -n hw.physicalcpu) \
          --config Release &&
        cd build &&
        mkdir Payload &&
        mv devilutionx.app Payload &&
        zip -r devilutionx-iOS.ipa Payload

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-iOS.ipa
        path: build/devilutionx-iOS.ipa

    - name: Update Release
      if: ${{ github.event_name == 'release' && !env.ACT }}
      uses: svenstaro/upload-release-action@v2
      with:
        file: build/devilutionx-iOS.ipa
        overwrite: true

    - name: Clean up artifacts
      run: rm -rf build/Payload build/*.ipa
...
