---
name: macOS x86_64

on:
  push:
    branches:
      - master
    paths-ignore:
      - '*.md'
      - 'docs/**'
  pull_request:
    types: [opened, synchronize]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  release:
    types: [published]
    paths-ignore:
      - '*.md'
      - 'docs/**'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Create Build Environment
      run: |
        brew update-reset
        brew update
        brew bundle install

    - name: Cache CMake build folder
      uses: actions/cache@v4
      with:
        path: build
        key: ${{ github.workflow }}-v2-${{ github.sha }}
        restore-keys: ${{ github.workflow }}-v2-

    - name: Configure CMake
      working-directory: ${{github.workspace}}
      shell: bash
      env:
        CMAKE_BUILD_TYPE: ${{github.event_name == 'release' && 'Release' || 'RelWithDebInfo'}}
      run: |
        cmake \
          -S . \
          -B build \
          -D CMAKE_TOOLCHAIN_FILE=../CMake/platforms/ios.toolchain.cmake \
          -D PLATFORM=MAC \
          -D CMAKE_BUILD_TYPE=${{env.CMAKE_BUILD_TYPE}} \
          -D BUILD_TESTING=OFF \
          -D MACOSX_STANDALONE_APP_BUNDLE=ON \
          -D DISCORD_INTEGRATION=ON

    - name: Build
      working-directory: ${{github.workspace}}
      shell: bash
      run: |
        cmake \
          --build build \
          -j $(sysctl -n hw.physicalcpu) \
          --target package && \
        mv build/devilutionx.dmg build/devilutionx-x86_64-macOS.dmg

    - name: Upload-Package
      if: ${{ !env.ACT }}
      uses: actions/upload-artifact@v4
      with:
        name: devilutionx-x86_64-macOS.dmg
        path: build/devilutionx-x86_64-macOS.dmg

    - name: Clean up artifacts
      run: rm -rf build/_CPack_Packages build/*.dmg
...
